CREATE TABLE IF NOT EXISTS get5_stats_matches (
	`matchid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`start_time` DATETIME NOT NULL,
	`end_time` DATETIME NOT NULL,
	`winner` VARCHAR(16) NOT NULL DEFAULT '',
	`series_type` VARCHAR(64) NOT NULL DEFAULT '',
	`team1_name` VARCHAR(64) NOT NULL DEFAULT '',
	`team1_score` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	`team2_name` VARCHAR(64) NOT NULL DEFAULT '',
	`team2_score` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (`matchid`));

CREATE TABLE IF NOT EXISTS get5_stats_maps (
	`matchid` INT UNSIGNED NOT NULL,
	`mapnumber` SMALLINT UNSIGNED NOT NULL,
	`start_time` DATETIME NOT NULL,
	`end_time` DATETIME NOT NULL,
	`winner` VARCHAR(16) NOT NULL DEFAULT '',
	`mapname` VARCHAR(64) NOT NULL DEFAULT '',
	`team1_score` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	`team2_score` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (`matchid`, `mapnumber`));

CREATE TABLE IF NOT EXISTS get5_stats_players (
	`matchid` INT UNSIGNED NOT NULL,
	`mapnumber` SMALLINT UNSIGNED NOT NULL,
	`steamid64` VARCHAR(32) NOT NULL,
	`team` VARCHAR(16) NOT NULL DEFAULT '',
	`rounds_played` SMALLINT UNSIGNED NOT NULL,
	`name` VARCHAR(64) NOT NULL,
	`kills` SMALLINT UNSIGNED NOT NULL,
	`deaths` SMALLINT UNSIGNED NOT NULL,
	`assists` SMALLINT UNSIGNED NOT NULL,
	`teamkills` SMALLINT UNSIGNED NOT NULL,
	`headshot_kills` SMALLINT UNSIGNED NOT NULL,
	`damage` INT NOT NULL,
	`bomb_plants` SMALLINT UNSIGNED NOT NULL,
	`bomb_defuses` SMALLINT UNSIGNED NOT NULL,
	`v1` SMALLINT UNSIGNED NOT NULL,
	`v2` SMALLINT UNSIGNED NOT NULL,
	`v3` SMALLINT UNSIGNED NOT NULL,
	`v4` SMALLINT UNSIGNED NOT NULL,
	`v5` SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY (`matchid`, `mapnumber`, `steamid64`));
